{% set version = "0.1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-forestly
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/forestly_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/forestly/forestly_{{ version }}.tar.gz
  sha256: bd8d56038a8ab68fbd7d8057352c66e9cb6f577336feae36c712525b17221646

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-brew
    - r-crosstalk
    - r-glue
    - r-htmltools
    - r-metalite
    - r-metalite.ae
    - r-reactr
    - r-reactable
    - r-rlang
  run:
    - r-base
    - r-brew
    - r-crosstalk
    - r-glue
    - r-htmltools
    - r-metalite
    - r-metalite.ae
    - r-reactr
    - r-reactable
    - r-rlang

test:
  commands:
    - $R -e "library('forestly')"           # [not win]
    - "\"%R%\" -e \"library('forestly')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=forestly
  license: GPL-3.0-or-later
  summary: Interactive forest plot for clinical trial safety analysis using 'metalite', 'reactable', 'plotly', and Analysis Data Model (ADaM) datasets. Includes functionality for adverse event filtering, incidence-based group filtering, hover-over reveals, and search and sort operations. The workflow allows for metadata
    construction, data preparation, output formatting, and interactive plot generation.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
